spec:
  course: Linear Algebra I
  group: Group Alpha
  members:
  - name: Max Mustermann
    id: "123456"
  - name: Erika Mustermann
    id: AB123456
  - name: Kim Took
    id: "69420"
  generate:
    create:
    - code
    - feedback
    - figures
  build:
    recipe:
    - command: latexmk.exe
      args:
      - -interaction=nonstopmode
      - -pdf
      - -file-line-error
      - -shell-escape
      - -outdir="{{.OUTDIR}}"
      - '{{.DOC}}'
    cleanup:
      glob: {}
  bundle:
    template: assignment-{{._id}}_{{.member1}}_{{.member2}}_{{.member3}}.{{._format}}
    data:
      member1: 123456
      member2: AB123456
      member3: 69420
    include:
    - code/**
    - feedback/**
    - figures/**
status:
  assignment: 4
