status:
  assignment: 2
spec:
  course: Linear Algebra I
  group: Group Alpha
  includes: []
  members:
  - name: Max Mustermann
    id: "123456"
  - name: Erika Mustermann
    id: AB123456
  - name: Kim Took
    id: "69420"
  template: ""
  generate:
    create:
    - code
    - feedback
    - figures
  build:
    recipe:
    - command: latexmk.exe
      args:
      - -interaction=nonstopmode
      - -pdf
      - -file-line-error
      - -shell-escape
  bundle:
    template: ""
    data: {}
    include: []
