spec:
    course: Linear Algebra I
    group: Group Alpha
    members:
        - id: "12346"
          name: Max Mustermann
        - id: AB123456
          name: Erika Mustermann
        - id: "69420"
          name: Kim Took
status:
    assignment: 1
